### ISSUE TITLE
OnDuplicatekey Map Loop unstable

### ISSUE THREAD

**Issue by 0ostreamo0** [orca-zhang/borm#4]
BuildSQL 和 BuildArgs 
在分两次遍历了arg里面的同一个map 每次map遍历不能保证用稳定顺序输出 
最后执行的语句里预处理语句和参数就可能不对称

#### [problem line]

app/common/live/library/borm/borm.go:544

```
// on duplicate key update
for _, arg := range args {
    arg.BuildSQL(&sb)
    arg.BuildArgs(&stmtArgs)
}
```

**Comment by Danceiny** [comment]
已经修掉了
https://github.com/orca-zhang/borm/commit/cdde4abe7ba5090cd3bd81fd3d036453ef0e5769

**Comment by orca-zhang** [comment]
> BuildSQL 和 BuildArgs
> 在分两次遍历了arg里面的同一个map 每次map遍历不能保证用稳定顺序输出
> 最后执行的语句里预处理语句和参数就可能不对称
> 
> #### [problem line]
> app/common/live/library/borm/borm.go:544
> 
> ```
> // on duplicate key update
> for _, arg := range args {
>     arg.BuildSQL(&sb)
>     arg.BuildArgs(&stmtArgs)
> }
> ```

#2 已修复，请pull最新代码，感谢反馈～
